import type OpenAI from 'openai';

/**
 * Reflection synthesis — periodically synthesize raw corrections into
 * higher-order voice rules. From simulacra paper Section 4.2:
 * "Reflections are higher-level, more abstract thoughts generated by the agent."
 *
 * Takes N raw corrections and produces consolidated voice rules that are
 * more useful than individual corrections.
 */

export interface ReflectionResult {
	rules: string[];
	correctionCount: number;
	timestamp: string;
}

const REFLECTION_PROMPT = `You are a voice consistency analyst. Given a list of corrections/feedback about how an AI voice agent should NOT sound, synthesize them into concise, actionable voice rules.

Each rule should:
1. Be specific and concrete (not vague like "be more natural")
2. Start with a verb (Avoid, Never, Always, Keep, Use, Don't)
3. Combine related corrections into single rules where possible
4. Prioritize rules that appeared multiple times or seem most impactful

Return a JSON array of strings, each being one voice rule. Maximum 8 rules.
Return ONLY valid JSON.`;

/**
 * Synthesize raw corrections into higher-order voice rules.
 * Called periodically (e.g. after every 5 corrections, or on demand).
 */
export async function synthesizeReflections(
	corrections: string[],
	openai: OpenAI,
	model = 'minimax/minimax-m2.7',
): Promise<ReflectionResult> {
	if (corrections.length === 0) {
		return { rules: [], correctionCount: 0, timestamp: new Date().toISOString() };
	}

	const correctionList = corrections.map((c, i) => `${i + 1}. ${c}`).join('\n');

	const response = await openai.chat.completions.create({
		model,
		messages: [
			{ role: 'system', content: REFLECTION_PROMPT },
			{
				role: 'user',
				content: `Here are ${corrections.length} corrections from users:\n\n${correctionList}`,
			},
		],
		temperature: 0.3,
	});

	const content = response.choices[0]?.message?.content;
	if (!content) {
		return { rules: [], correctionCount: corrections.length, timestamp: new Date().toISOString() };
	}

	try {
		const cleaned = content.replace(/^```json\n?|```$/g, '').trim();
		const rules = JSON.parse(cleaned) as string[];
		return {
			rules: Array.isArray(rules) ? rules : [],
			correctionCount: corrections.length,
			timestamp: new Date().toISOString(),
		};
	} catch {
		return { rules: [], correctionCount: corrections.length, timestamp: new Date().toISOString() };
	}
}
